import {test,expect} from '@playwright/test';
import {recordPath} from './record-helpers';
for(const width of [1470,390]) test(`illustrated About remains readable and its actions work at ${width}`,async({page})=>{
  await page.setViewportSize({width,height:900});
  await page.goto(recordPath+'?view=about');
  const about=page.locator('[data-about-view]');
  await expect(about).toBeVisible();
  expect(await about.locator('.about-art').evaluate(n=>getComputedStyle(n).backgroundImage)).toContain('about-city.webp');
  expect((await page.request.get('/images/record/about-city.webp')).status()).toBe(200);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
  expect(await page.locator(".topbar").evaluate(n=>getComputedStyle(n).backdropFilter)).toBe("none");
  await page.waitForTimeout(350);
  await page.screenshot({path:`/private/tmp/cif-about-city-${width}.png`,fullPage:true});
  const principles=about.locator('.about-principle');
  await principles.nth(0).locator('summary').click();
  await expect(principles.nth(0)).toHaveAttribute('open','');
  await principles.nth(1).locator('summary').click();
  await expect(principles.nth(1)).toHaveAttribute('open','');
  await expect(principles.nth(0)).not.toHaveAttribute('open','');
  await page.locator('.about-scroll').evaluate(n=>n.scrollTop=500);
  await expect(about.locator('.about-footer, .record-history')).toHaveCount(0);
  await page.screenshot({path:`/private/tmp/cif-about-expanded-${width}.png`,fullPage:true});
  await about.locator('.about-contribute-link').click();
  await expect(page.locator('[data-contribution-view]')).toBeVisible();
  await expect(page.locator('[data-contribution-view] textarea')).toBeVisible();
  await page.locator('[data-contribution-choice="follow"]').click();
  await expect(page.locator('[data-contribution-panel="follow"]')).toBeVisible();
  await page.locator('[data-contribution-choice="suggest"]').click();
  await expect(page.locator('[data-contribution-panel="suggest"]')).toBeVisible();
  await page.locator('.about-scroll').evaluate(n=>n.scrollTop=n.scrollHeight);
  await page.waitForTimeout(300);
  await expect(about).toBeVisible();
  await expect(page.locator('.atlas-nav [data-open-contribution]')).toHaveCount(0);
  await page.screenshot({path:`/private/tmp/cif-about-form-${width}.png`,fullPage:true});
  expect(await page.evaluate(()=>window.scrollY)).toBe(0);
  expect(await page.evaluate(()=>document.documentElement.scrollHeight-innerHeight)).toBeLessThanOrEqual(1);
});
