import {test,expect} from '@playwright/test';
test('scroll follows input, navigation glides, and long passages stay readable',async({page})=>{
 await page.setViewportSize({width:1280,height:900});
 await page.goto('/work/coexisting-with-ai/record/explore/?question=creativity');
 await page.getByRole('button',{name:'Let’s explore'}).click();
 await page.locator('[data-view="creativity"] .explore-position-row').filter({hasText:'Mike Todasco'}).click();
 await page.waitForTimeout(1200);
 await page.getByRole('button',{name:'Go to perspectives',exact:true}).click();
 await page.waitForTimeout(1200);
 await page.mouse.move(600,400);
 const start=await page.evaluate(()=>scrollY);
 await page.mouse.wheel(0,80);await page.waitForTimeout(800);
 const moved=await page.evaluate(()=>scrollY);
 expect(moved-start).toBeGreaterThan(30);expect(moved-start).toBeLessThan(170);
 await page.mouse.wheel(0,-50);await page.waitForTimeout(150);
 expect(await page.evaluate(()=>scrollY)).toBeLessThan(moved);
 await page.getByRole('button',{name:'Go to keep exploring',exact:true}).click();
 await page.waitForTimeout(120);
 const during=await page.evaluate(()=>scrollY);
 await page.mouse.wheel(0,-60);await page.waitForTimeout(400);
 expect(await page.evaluate(()=>scrollY)).toBeLessThan(during+100);
 await page.getByRole('button',{name:'Go to reading',exact:true}).click();
 await expect.poll(async()=>Math.round((await page.locator('.record-perspective').boundingBox())!.y)).toBe(94);
 await page.locator('[data-context-toggle]').click();
 await page.locator('[data-context-read]').click();
 for(const summary of await page.locator('[data-inspector-transcript] .source-more summary').all())await summary.click();
 const last=page.locator('[data-inspector-transcript] .source-turn p').last();
 await last.scrollIntoViewIfNeeded();await expect(last).toBeInViewport();
});
