import {test,expect} from '@playwright/test';
import fs from 'node:fs';
const prompts=JSON.parse(fs.readFileSync('src/data/record-reflections.json','utf8'));
const editorial=JSON.parse(fs.readFileSync('src/data/record-editorial.json','utf8'));
const path='/work/coexisting-with-ai/record/explore/?question=understanding';
async function start(page){await page.goto(path);await page.getByRole('button',{name:'Let’s explore'}).click();await page.locator('[data-view="understanding"] .explore-position-row').first().click();await page.waitForTimeout(1100);}
test('every featured passage has a question and distinct valid choices',()=>{expect(Object.keys(prompts).sort()).toEqual(Object.keys(editorial).sort());for(const [key,p] of Object.entries<any>(prompts)){expect(p.question.endsWith('?')).toBeTruthy();expect(p.options.length).toBe(2);expect(new Set(p.options.map(o=>o.target)).size).toBe(2);for(const option of p.options){expect(editorial[option.target]).toBeTruthy();expect(option.target).not.toBe(key);expect(option.explanation.length).toBeGreaterThan(60);}}});
for(const width of [390,1440])test(`answers change suggestions and preserve the explored path at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.emulateMedia({reducedMotion:'reduce'});await start(page);
 const first=page.locator('.source-section');const reflection=first.locator('.journey-reflection');const next=first.locator('.reflection-next');
 await expect(reflection.getByRole('heading')).toHaveText('What would you look for before saying an AI understands?');
 await reflection.locator('[data-reflection-option="1"]').click();await expect(next).toContainText('You chose explanations.');await expect(reflection.locator('[data-reflection-option="1"]')).toHaveAttribute('aria-pressed','true');
 await next.locator('.onward-source').first().click();await expect(page.locator('.journey-history>section')).toHaveCount(2);const title=await page.locator('.journey-chapter .reading-title').textContent();
 await reflection.scrollIntoViewIfNeeded();const before=await page.evaluate(()=>scrollY);await reflection.locator('[data-reflection-option="2"]').click();await expect(next).toContainText('You chose unfamiliar situations.');await expect(page.locator('.journey-chapter .reading-title')).toHaveText(title!);await expect(page.locator('.journey-history>section')).toHaveCount(2);expect(Math.abs((await page.evaluate(()=>scrollY))-before)).toBeLessThanOrEqual(1);
 await reflection.locator('[data-reflection-option="1"]').click();await expect(next).toContainText('already in your journey');await next.locator('.onward-source').first().click();await expect(page.locator('.journey-history>section')).toHaveCount(2);
 await reflection.scrollIntoViewIfNeeded();await page.screenshot({path:`/tmp/cif-reflection-${width}.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});
test('private answers and notes survive reload but are absent from a shared journey',async({page,browser})=>{await page.emulateMedia({reducedMotion:'reduce'});await start(page);let reflection=page.locator('.source-section .journey-reflection');await reflection.locator('[data-reflection-option="2"]').click();await reflection.locator('.reflection-note summary').click();await reflection.getByLabel('Your note',{exact:true}).fill('A private thought about my own learning.');const url=page.url();expect(decodeURIComponent(url)).not.toContain('private thought');expect(decodeURIComponent(url)).not.toContain('choice');await page.reload();reflection=page.locator('.source-section .journey-reflection');await expect(reflection.locator('[data-reflection-option="2"]')).toHaveAttribute('aria-pressed','true');await reflection.locator('.reflection-note summary').click();await expect(reflection.getByLabel('Your note',{exact:true})).toHaveValue('A private thought about my own learning.');const other=await browser.newContext();try{const shared=await other.newPage();await shared.goto(url);await expect(shared.locator('.reflection-option[aria-pressed=true]')).toHaveCount(0);await expect(shared.locator('.reflection-note textarea')).toHaveValue('');}finally{await other.close();}await reflection.getByRole('button',{name:'Clear my note'}).click();await expect(reflection.getByLabel('Your note',{exact:true})).toHaveValue('');});
test('skip leaves navigation available and keyboard choices work',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await start(page);const reflection=page.locator('.source-section .journey-reflection');const choice=reflection.locator('.reflection-option').first();await choice.focus();await choice.press('Enter');await expect(choice).toHaveAttribute('aria-pressed','true');await reflection.getByRole('button',{name:'Continue without answering'}).click();await expect(reflection.locator('.reflection-option[aria-pressed=true]')).toHaveCount(0);await expect(page.locator('.source-section .reflection-next .onward-source').first()).toBeVisible();await expect(reflection).toContainText('You can answer later.');});
